node{
  def Namespace = "default"
  def ImageName = "sg4j/jenkins-jnlp-worker-maven"

  try{
      stage('Checkout'){
          git 'https://github.com/sg4j/simple-java-maven-app.git'
          sh "git rev-parse --short HEAD > .git/commit-id"
      }
        stage('Build') {
          sh 'mvn -B -DskipTests clean package'
        
        }
        stage('Unit Test') { 
                sh 'mvn test' 
                    junit 'target/surefire-reports/*.xml' 
        }
   }catch (err) {
      currentBuild.result = 'FAILURE'
    }
}
